core = 7.x
api = 2

; Modules =====================================================================
projects[drupal_ipsum][subdir] = "contrib"
;projects[admin][subdir] = "contrib"
projects[admin_menu][subdir] = "contrib"
projects[ctools][version] = "1.x-dev"
projects[ctools][subdir] = "contrib"
projects[devel][subdir] = "contrib"
projects[entity_view_mode][subdir] = "contrib"
projects[file_entity][version] = "2.0-alpha3"
projects[file_entity][subdir] = "contrib"
;projects[media_gallery][version] = "2.x-dev"
;projects[media_gallery][subdir] = "contrib"
projects[flexslider][subdir] = "contrib"
;projects[flexslider_views_slideshow][subdir] = "contrib"
projects[jquery_update][subdir] = "contrib"
;projects[less][version] = "3.x-dev"
;projects[less][subdir] = "contrib"
projects[libraries][subdir] = "contrib"
;projects[manual-crop][subdir] = "contrib"
projects[module_filter][subdir] = "contrib"
projects[panels][subdir] = "contrib"
;projects[panels_bootstrap_layouts][subdir] = "contrib"
projects[text_resize][subdir] = "contrib"
projects[views][subdir] = "contrib"
projects[views_bootstrap][version] = "3.x-dev"
projects[views_bootstrap][subdir] = "contrib"
;projects[views_slideshow][subdir] = "contrib"
projects[features][subdir] = "contrib"
projects[features][version] = "2.0"
projects[features][patch][] = "https://drupal.org/files/issues/features_strict-warning-menu-links_2155945-3.patch"
projects[strongarm][subdir] = "contrib"
projects[diff][subdir] = "contrib"
projects[ckeditor][subdir] = "contrib"
;projects[uuid][subdir] = "contrib"
projects[entity][subdir] = "contrib"
;projects[uuid_features][version] = "1.x-dev"
;projects[uuid_features][subdir] = "contrib"
projects[date][subdir] = "contrib"
;projects[calendar][subdir] = "contrib"
;projects[calendar][patch][] = "https://drupal.org/files/1471400-12.patch"
projects[feeds][subdir] = "contrib"
projects[transliteration][subdir] = "contrib"
projects[job_scheduler][subdir] = "contrib"
projects[workbench][subdir] = "contrib"
projects[workbench_media][subdir] = "contrib"
projects[workbench_media][version] = "2.1"
projects[panels_breadcrumbs][subdir] = "contrib"
;projects[edit][version] = "1.x-dev"
projects[edit][subdir] = "contrib"
projects[l10n_update][subdir] = "contrib"
;projects[l10n_client][subdir] = "contrib"
projects[media][version] = "2.0-alpha3"
projects[media][subdir] = "contrib"
;projects[genpass][subdir] = "contrib"
;projects[field_collection][version] = "1.x-dev"
projects[field_collection][subdir] = "contrib"
;projects[field_group][subdir] = "contrib"
projects[rules][subdir] = "contrib"
projects[honeypot][subdir] = "contrib"
;projects[pathauto][version] = "1.x-dev"
projects[pathauto][subdir] = "contrib"
;projects[link][version] = "1.x-dev"
projects[link][subdir] = "contrib"
projects[token][subdir] = "contrib"
;projects[colorbox][version] = "2.x-dev"
projects[colorbox][subdir] = "contrib"
;projects[modal_forms][version] = "1.x-dev"
;projects[modal_forms][subdir] = "contrib"
;projects[quicktabs][version] = "3.x-dev"
;projects[quicktabs][subdir] = "contrib"
;projects[quicktabs][patch][] = "https://drupal.org/files/missing-ampersand-for-tab-creation.patch" 
projects[media_colorbox][subdir] = "contrib"
;projects[media_browser_plus][version] = "3.x-dev"
;projects[media_browser_plus][subdir] = "contrib"
;projects[views_bulk_operations][version] = "3.x-dev"
;projects[views_bulk_operations][subdir] = "contrib"
projects[multiform][subdir] = "contrib"
;projects[views_tree][subdir] = "contrib"
;projects[menu_rules][subdir] = "contrib"
projects[plupload][subdir] = "contrib"
projects[email][version] = "1.x-dev"
projects[email][subdir] = "contrib"
;projects[entityreference][version] = "1.x-dev"
projects[entityreference][subdir] = "contrib"
;projects[menu_attributes][version] = "1.x-dev"
;projects[menu_attributes][subdir] = "contrib"
;projects[nodequeue][version] = "2.x-dev"
;projects[nodequeue][subdir] = "contrib"
;projects[panels_extra_styles][version] = "1.x-dev"
;projects[panels_extra_styles][subdir] = "contrib"
projects[shs][versions] = "1.x-dev"
projects[shs][subdir] = "contrib"
projects[special_menu_items][subdir] = "contrib"
projects[date_repeat_instance][subdir] = "contrib"
;projects[plup][subdir] = "contrib"
;projects[fancybox][subdir] = "contrib"
projects[menu_block][subdir] = "contrib"
;projects[editableviews][subdir] = "contrib"
;projects[editableviews][version] = "1.x-dev"
;projects[auto_username][subdir] = "contrib"
;projects[auto_username][version] = "1.x-dev"
;projects[fblikebutton][version] = "2.x-dev"
;projects[fblikebutton][subdir] = "contrib"
;projects[fb_autopost][version] = "1.x-dev"
projects[fb_autopost][subdir] = "contrib"
;projects[menu_breadcrumb][subdir] = "contrib"
;projects[pathauto_persist][subdir] = "contrib"
projects[menu_editor][subdir] = "contrib"
projects[location][subdir] = "contrib"
projects[relation][subdir] = "contrib"
projects[relation][version] = "1.x-dev"
projects[relation_add][subdir] = "contrib"
projects[relation_add][version] = "1.1"
projects[relation_add][patch][] = "https://drupal.org/files/relation_add-fix_reference_error-2083101-2.patch"
projects[gmap][subdir] = "contrib"
projects[taxonomy_menu][subdir] = "contrib"
projects[migrate][version] = "2.x-dev"
projects[migrate][subdir] = "contrib"
projects[path_breadcrumbs][subdir] = "contrib"
projects[views_limit_grouping][subdir] = "contrib"
projects[panels_bootstrap_styles][subdir] = "contrib"
projects[social_media_links][subdir] = "contrib"
projects[social_media_links][version] = "1.x-dev"
projects[features_extra][subdir] = "contrib"
projects[entityqueue][subdir] = "contrib"
projects[entityqueue][version] = "1.x-dev"
projects[fb_social][version] = "2.x-dev"
projects[fb_social][subdir] = "contrib"
projects[ajax_poll][subdir] = "contrib"
projects[pm_existing_pages][subdir] = "contrib"

projects[bootstrap_panels_horizontal_tabs][type] = "module"
projects[bootstrap_panels_horizontal_tabs][directory_name] = "fap_panels_horizontal_tabs"
projects[bootstrap_panels_horizontal_tabs][subdir] = "contrib"
projects[bootstrap_panels_horizontal_tabs][download][type] = "git"
projects[bootstrap_panels_horizontal_tabs][download][url] = "http://git.drupal.org/sandbox/ShaunDychko/2126611.git"
projects[bootstrap_panels_horizontal_tabs][branch] = "7.x-1.x"

; Custom themes and features ======================================================================

projects[skeidgnup_theme][type] = "theme"
projects[skeidgnup_theme][directory_name] = "skeidgnup_theme"
projects[skeidgnup_theme][download][type] = "git"
projects[skeidgnup_theme][download][url] = "https://github.com/busla/skeidgnup-theme.git"
projects[skeidgnup_theme][branch] = "master"

projects[municipality_app][type] = "module"
projects[municipality_app][subdir] = "custom"
projects[municipality_app][download][type] = "git"
projects[municipality_app][download][url] = "https://github.com/busla/municipality-app.git"
projects[municipality_app][branch] = "master"

projects[skeidgnup_migrate][type] = "module"
projects[skeidgnup_migrate][subdir] = "custom"
projects[skeidgnup_migrate][download][type] = "git"
projects[skeidgnup_migrate][download][url] = "https://github.com/busla/skeidgnup-migrate.git"
projects[skeidgnup_migrate][branch] = "master"

; Libraries ======================================================================

; Bootstrap 3.0.3
libraries[bootstrap][download][type] = "get"
libraries[bootstrap][download][url] = "https://github.com/twbs/bootstrap/archive/v3.0.3.zip"
libraries[bootstrap][directory_name] = "bootstrap"
libraries[bootstrap][destination] = "themes/skeidgnup_theme"
libraries[bootstrap][overwrite] = TRUE

; Colorbox
libraries[colorbox][type] = "library"
libraries[colorbox][download][type] = "file"
libraries[colorbox][download][url] = "https://github.com/jackmoore/colorbox/archive/master.zip"
libraries[colorbox][directory_name] = "colorbox"

; Ckeditor
libraries[ckeditor][type] = "library"
libraries[ckeditor][download][type] = "file"
libraries[ckeditor][download][url] = "http://download.cksource.com/CKEditor/CKEditor/CKEditor%204.3/ckeditor_4.3_full.zip"
libraries[ckeditor][directory_name] = "ckeditor"


; Plupload
libraries[plupload][type] = "library"
libraries[plupload][download][type] = "file"
libraries[plupload][download][url] = "https://github.com/moxiecode/plupload/archive/v1.5.8.zip"
libraries[plupload][directory_name] = "plupload"


;Facebook SDK
projects[facebook-php-sdk][type] = "library"
projects[facebook-php-sdk][download][type] = "git"
projects[facebook-php-sdk][download][url] = "https://github.com/facebook/facebook-php-sdk"
projects[facebook-php-sdk][directory_name] = "facebook-php-sdk"
projects[facebook-php-sdk][branch] = "master"

; Themes ======================================================================

;projects[] = "tao"
;projects[] = "rubik"
projects[] = "adminimal_theme"
projects[bootstrap][version] = "3.x-dev"
projects[bootstrap][patch][] = "https://drupal.org/files/issues/bootstrap-2153689-1-aggressive_scroll.patch"
